name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
      - develop
      - 'release/**'
      - 'feature/**'

jobs:
  test:
    name: Run Pull Request Checks
    runs-on: ubuntu-18.04


    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Unit Tests
        run: ./gradlew testDevDebug
      - name: Run Static Analysis Checks
        run: ./gradlew detekt ktlint lintDevDebug spotlessCheck --daemon
